controller_manager:
  ros__parameters:
    update_rate: 100  # 100 Hz standarttır
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    my_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true

my_arm_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - joint1
      - joint2
      - joint3
    
    # Position only modunda kalıyoruz, en güvenlisi bu
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
    
    # Hata önleyiciler
    allow_partial_joints_goal: true
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    
    # --- DÜZELTME BURADA: GÜCÜ DÜŞÜRDÜK ---
    # Eski: 5000.0 (Çok titrer ve Abort verir)
    # Yeni: 200.0 (Daha yumuşak ve kararlı)
    gains:
      joint1: {p: 200.0, i: 10.0, d: 0.5, i_clamp: 1.0}
      joint2: {p: 200.0, i: 10.0, d: 0.5, i_clamp: 1.0}
      joint3: {p: 200.0, i: 10.0, d: 0.5, i_clamp: 1.0}

    # Toleranslar hala kapalı (Sınırsız)
    constraints:
      goal_time: 0.0
      stopped_velocity_tolerance: 0.0
      joint1: {trajectory: 0.0, goal: 0.0}
      joint2: {trajectory: 0.0, goal: 0.0}
      joint3: {trajectory: 0.0, goal: 0.0}
